---
name: marcelocorreia/base-ruby
github_user: marcelocorreia
git_repo: docker-base-ruby
docker_namespace: marcelocorreia
docker: https://hub.docker.com/u/marcelocorreia
github: https://github.com/marcelocorreia
dockerfile: Dockerfile
#logo: https://i2.wp.com/killscreen.com/wp-content/uploads/2016/08/bastion-gameplay.jpg?fit=700%2C396&ssl=1
#docs: https://your.docs.com
linkedin: https://www.linkedin.com/in/marcelocorreia/
#website: https://your.website.com
slack: https://correia-group.slack.com/
#email: marcelo@correia.io
blueprint: docker/image

overview: |
  Docker Ruby Base image

dockerfiles:
  - Dockerfile

usage: |
  ```bash
  $ docker run --rm marcelocorreia/base-ruby node -v

  ```
  ## Setting timezone
  ```bash
  $ docker run --rm -e TZ=Australia/Sydney marcelocorreia/base-ruby node -v
  ```
  ### Extending
  ```Dockerfile
  FROM marcelocorreia/base-ruby
  ...
  ```
  **Targets**
  ```bash
  $ make release
  $ make build
  $ make push
  $ make all-versions
  $ make current-version
  $ make next-version
  ```

shields:
  - https://img.shields.io/docker/pulls/{{.name}}.svg
  - https://img.shields.io/github/languages/top/{{ .github_user }}/{{ .git_repo }}.svg
tldr:
  - '[Overview](#overview)'
  - '[Description](#description)'
  - '[Dockerfile](#dockerfile)'
  - '[Usage](#usage)'
  - '[License](#license)'

licenses:
  - apache-license